# -*- coding:utf-8 -*- 
# @Time: 2022/2/11
# @Author: zxw
# @Name: ice_duang_duang
# @Software: PyCharm


import turtle

def bgpic(self, picname=None):
    if picname is None:
        return self._bgpicname
    if picname not in self._bgpics:
        self._bgpics[picname] = self._image(picname)
    self._setbgpic(self._bgpic, self._bgpics[picname])
    self._bgpicname = picname


def drawpic():

    turtle.speed(100)  # 速度
    turtle.pensize(3)

    # 底座
    turtle.penup()
    turtle.goto(-250, -150)
    turtle.pendown()
    turtle.pencolor("cyan")
    turtle.fillcolor("cyan")
    turtle.begin_fill()
    turtle.setheading(180)
    turtle.circle(50, 180)
    turtle.fd(500)
    turtle.circle(50, 180)
    turtle.fd(500)
    turtle.end_fill()

    # 右手
    turtle.penup()
    turtle.goto(95, 55)
    turtle.pendown()
    turtle.pencolor("lightgray")
    turtle.fillcolor("black")

    turtle.begin_fill()
    turtle.setheading(-40)
    turtle.circle(250, 18)
    turtle.circle(-20, 170)
    turtle.circle(-140, 20)
    turtle.setheading(90)
    turtle.circle(185, 20)
    turtle.end_fill()

    # 头顶
    turtle.penup()
    turtle.goto(-140, 130)
    turtle.pencolor("lightgray")
    turtle.fillcolor("white")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(40)
    turtle.circle(-180, 42)
    # 右耳
    turtle.setheading(50)
    turtle.circle(-35, 160)
    # 右侧
    turtle.setheading(-40)
    turtle.circle(-180, 30)
    turtle.setheading(-76)
    turtle.circle(-320, 30)
    # 右腿
    turtle.circle(120, 18)
    turtle.fd(30)
    turtle.circle(-18, 85)
    turtle.circle(-180, 10)
    turtle.circle(-20, 110)
    turtle.circle(15, 115)
    turtle.circle(100, 12)
    # 左腿
    turtle.circle(15, 90)
    turtle.fd(10)
    turtle.circle(-15, 100)
    turtle.circle(-200, 10)
    turtle.circle(-15, 70)
    turtle.circle(-150, 15)
    turtle.circle(20, 35)
    # 左侧
    turtle.setheading(140)
    turtle.circle(-220, 60)
    # 左耳
    turtle.setheading(150)
    turtle.circle(-30, 170)
    turtle.end_fill()

    # 左耳内
    turtle.penup()
    turtle.goto(-163, 86)
    turtle.pencolor("black")
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(145)
    turtle.circle(-22, 165)
    turtle.setheading(235)
    turtle.circle(150, 16)
    turtle.end_fill()

    # 右耳内
    turtle.penup()
    turtle.goto(-8, 172)
    turtle.setheading(40)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(-28, 150)
    turtle.setheading(140)
    turtle.circle(150, 21.2)
    turtle.end_fill()

    # 左腿内
    turtle.penup()
    turtle.goto(-20, -148)
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(-145)
    turtle.circle(15, 90)
    turtle.circle(-12, 120)
    turtle.circle(-200, 9)
    turtle.circle(-15, 70)
    turtle.circle(-150, 15)
    turtle.circle(20, 35)
    turtle.setheading(-35)
    turtle.circle(120, 33)
    turtle.end_fill()

    # 右腿内
    turtle.penup()
    turtle.goto(86, -110)
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(-100)
    turtle.circle(160, 21)
    turtle.circle(-13, 90)
    turtle.circle(-180, 10)
    turtle.circle(-20, 115)
    turtle.circle(15, 90)
    turtle.setheading(7)
    turtle.circle(120, 36)
    turtle.end_fill()


    # 左眼
    # 眼圈
    turtle.penup()
    turtle.goto(-110, 65)
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(60)
    turtle.circle(-25, 165)
    turtle.circle(-170, 16)
    turtle.setheading(-150)
    turtle.circle(-30, 132)
    turtle.circle(-70, 28)
    turtle.end_fill()
    # 眼珠
    turtle.penup()
    turtle.goto(-85, 32)
    turtle.pencolor("white")
    turtle.fillcolor("white")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(0)
    turtle.circle(18, 360)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-85, 37)
    turtle.pencolor("black")
    turtle.fillcolor("darkslategray")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(0)
    turtle.circle(13, 360)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-85, 41)
    turtle.pencolor("black")
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(0)
    turtle.circle(6, 360)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-88, 50)
    turtle.pencolor("white")
    turtle.fillcolor("white")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(0)
    turtle.circle(3, 360)
    turtle.end_fill()

    # 右眼
    # 眼圈
    turtle.penup()
    turtle.goto(-20, 76)
    turtle.pencolor("black")
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(120)
    turtle.circle(-25, 152)
    turtle.circle(-100, 40)
    turtle.setheading(-90)
    turtle.circle(-20, 110)
    turtle.circle(-100, 36)
    turtle.end_fill()
    # 眼珠
    turtle.penup()
    turtle.goto(10, 62)
    turtle.pencolor("white")
    turtle.fillcolor("white")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(0)
    turtle.circle(18, 360)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(10, 66)
    turtle.pencolor("black")
    turtle.fillcolor("darkslategray")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(0)
    turtle.circle(13, 360)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(10, 70)
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(0)
    turtle.circle(6, 360)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(6, 78)
    turtle.pencolor("white")
    turtle.fillcolor("white")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(0)
    turtle.circle(3, 360)
    turtle.end_fill()

    # 鼻子
    turtle.penup()
    turtle.goto(-32, 65)
    turtle.pencolor("black")
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(10)
    turtle.circle(-6, 120)
    turtle.circle(-18, 90)
    turtle.circle(-6, 120)
    turtle.end_fill()

    # 嘴
    turtle.penup()
    turtle.goto(-60, 32)
    turtle.setheading(-30)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(40, 90)
    turtle.setheading(-110)
    turtle.circle(-40, 30)
    turtle.circle(-30, 50)
    turtle.circle(-40, 30)
    turtle.end_fill()

    # 彩虹圈
    turtle.penup()
    turtle.goto(-135, 90)
    turtle.pensize(3)
    turtle.pencolor("cyan")
    turtle.pendown()
    turtle.setheading(50)
    turtle.circle(-140, 70)
    turtle.circle(-80, 110)
    turtle.circle(-150, 50)
    turtle.circle(-89, 123)
    turtle.penup()
    turtle.goto(-135, 88)
    turtle.pencolor("slateblue")
    turtle.pendown()
    turtle.setheading(50)
    turtle.circle(-140, 70)
    turtle.circle(-80, 110)
    turtle.circle(-150, 50)
    turtle.circle(-89, 123)
    turtle.penup()
    turtle.goto(-135, 84)
    turtle.pencolor("orangered")
    turtle.pendown()
    turtle.setheading(51)
    turtle.circle(-140, 70)
    turtle.circle(-80, 110)
    turtle.circle(-150, 50)
    turtle.circle(-89, 123)
    turtle.penup()
    turtle.goto(-135, 94)
    turtle.pencolor("gold")
    turtle.pendown()
    turtle.setheading(50)
    turtle.circle(-144, 70)
    turtle.circle(-84, 110)
    turtle.circle(-154, 50)
    turtle.circle(-94, 123)
    turtle.penup()
    turtle.goto(-135, 82)
    turtle.pencolor("greenyellow")
    turtle.pendown()
    turtle.setheading(50)
    turtle.circle(-139, 68)
    turtle.circle(-75, 108)
    turtle.circle(-140, 50)
    turtle.circle(-88, 123)
    turtle.penup()

    #左手
    turtle.penup()
    turtle.goto(-210, -30)
    turtle.pencolor("lightgray")
    turtle.pensize(3)
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(140)
    turtle.circle(-30, 180)
    turtle.circle(-300, 8)
    turtle.circle(-30, 170)
    turtle.circle(-150, 15)
    turtle.end_fill()

    # 爱心
    turtle.penup()
    turtle.goto(-195, -5)
    turtle.pencolor("brown")
    turtle.pensize(1)
    turtle.fillcolor("brown")
    turtle.begin_fill()
    turtle.pendown()
    turtle.setheading(130)
    turtle.circle(-8, 180)
    turtle.circle(-60, 24)
    turtle.setheading(200)
    turtle.circle(-60, 24)
    turtle.circle(-8, 180)
    turtle.end_fill()


    #文字
    turtle.pensize(3)
    turtle.penup()
    turtle.pencolor("black")
    turtle.goto(-50, -110)
    # turtle.write("BEIJING 2022", font=('Arial', 10, 'bold italic'))
    # turtle.hideturtle()
    # 将文字显示为一个圆圈

    text = "BEIJING"
    turtle.pu()
    for i in text:
        turtle.write(i, font='consolas')
        turtle.rt(-5)
        turtle.pu()
        turtle.fd(8)
    text = "2022"
    turtle.pu()
    turtle.setheading(0)
    turtle.goto(15, -95)
    for i in text:
        turtle.write(i, font='consolas')
        turtle.rt(-5)
        turtle.pu()
        turtle.fd(8)
    turtle.hideturtle()


    # 五环
    turtle.pensize(2)
    turtle.penup()
    turtle.goto(-5, -125)
    turtle.pendown()
    turtle.pencolor("blue")
    turtle.circle(6)
    turtle.penup()
    turtle.goto(10, -120)
    turtle.pendown()
    turtle.pencolor("black")
    turtle.circle(6)
    turtle.penup()
    turtle.goto(25, -115)
    turtle.pendown()
    turtle.pencolor("brown")
    turtle.circle(6)
    turtle.penup()
    turtle.goto(4, -130)
    turtle.pendown()
    turtle.pencolor("lightgoldenrod")
    turtle.circle(6)
    turtle.penup()
    turtle.goto(20, -125)
    turtle.pendown()
    turtle.pencolor("green")
    turtle.circle(6)
    turtle.penup()




if __name__ == '__main__':

    turtle.hideturtle()
    turtle.colormode(255)
    turtle.setup(800, 600)
    drawpic()
    turtle.done()






